from tkinter import *
root = Tk()
root.title('Tests Demo')
root.geometry("450x500")
intro = Label(root, text="Registration form", font=("Arial", 15, ))
intro.grid(row=0, column=1)
full_name = Entry(root, width=20)
full_name.grid(row=1, column=1)
full_name = Label(root, text="fullname", width=9)
full_name.grid(row=1, column=0, pady=20)
email = Entry(root, width=20)
email.grid(row=2, column=1)
email = Label(root, text="email", width=6)
email.grid(row=2, column=0, pady=20)
radio = IntVar()
gender = Label(root, text="Gender")
gender.grid(row=3, column=0)
male = Radiobutton(root, text="Male", var=radio, width=5, value=1)
male.grid(row=3, column=1)
female = Radiobutton(root, text="Female", var=radio, width=5, value=0)
female.grid(row=3, column=2, pady=30)
country = Label(root, text="Country")
country.grid(row=4, column=0)
options = ["India", "USA", "France", "Germany", "UK"]
clicked = StringVar()
clicked.set("select your country")
drop = OptionMenu(root, clicked, *options)
drop.grid(row=4, column=1, pady=30)
v1 = IntVar()
v2 = IntVar()
programming = Label(root, text="programming")
programming.grid(row=5, column=0)
checkbox1 = Checkbutton(root, text='Java', variable=v1, onvalue=1, offvalue=0)
checkbox1.grid(row=5, column=1)
checkbox2 = Checkbutton(root, text='Python', variable=v2, onvalue=1, offvalue=0)
checkbox2.grid(row=5, column=2,)
submit = Button(root, text="Submit", bg="red", fg="white", width=20).grid(row=6, column=0)
delete_rec = Button(root, text="Delete Record", bg="cyan", fg="red", width=20).grid(row=6, column=1)
display_elements = Button(root, text="Submit", bg="orange", fg="white", width=20).grid(row=6, column=2)
root.mainloop()
